### PR TITLE
Parameterize deployment strategy type

### PR DESCRIPTION
**Pull request by chrodriguez**
Hi, I've installed jackett using your chart, and as I'm using a pv with RWO access mode, pod refuses to be created as it cant mount previosuly used volume. That's the reason of this PR

### CODE REVIEW

**Comment by halkeye** [comment]
\o/ Just to keep standard with my other charts, i'm going to make a "suggestion", but otherwise looks good

can you also bump the chart version?

**Comment by chrodriguez** [comment]
I think checking for this value is not necessary because defaults to RollingUpdate. I thin is unnecessary, what do you think?

**Comment by halkeye** [comment]
> I think checking for this value is not necessary because defaults to RollingUpdate. I thin is unnecessary, what do you think?

I've been bit by it a few times now, helm does a merge of values. If you change your deployment from rolling update to recreate, it'll still have the rollingupdate key, but it doesn't pass validation and fails to apply.

This just forces it to be null for anyone who already has it installed as rolling, your right, since the thing doesn't work as rolling, its probably not a big deal, but I like to keep things standard across my charts.

**Comment by halkeye** [comment]
\o/ https://ci.g4v.dev/job/halkeye-helm-charts/job/jackett-chart/job/v0.1.2/1/ is released

**Pull request merged**
